// End-to-end check: pack the generator the way npm would, scaffold an app from the tarball, then install, type-check and build it.
//
//   pnpm test
//
// The tests share one scaffolded app and each takes it further, so the suite runs with `concurrency: 1`. An early failure leaves the later tests nothing to work from — read the first failure, not the last.

import assert from 'node:assert/strict'
import { after, before, describe, test } from 'node:test'
import { execFileSync } from 'node:child_process'
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

const APP_ID = 'app.example.e2e'
const APP_NAME = 'E2E'
const APP_AUTHOR = 'Nobody'
const APP_DESCRIPTION = 'Generated by the e2e test'

/** Files the built package must contain. */
const EXPECTED = ['appmeta/manifest.json', 'scripts/main.js']
/** Repository files that must never be packaged as app resources. */
const FORBIDDEN = ['resources/package.json', 'resources/README.md', 'resources/tsconfig.json']

/** Runs a command, raising an error that carries the command's own output. */
function run(cmd, args, opts = {}) {
  try {
    return execFileSync(cmd, args, { encoding: 'utf8', stdio: 'pipe', ...opts })
  } catch (err) {
    const output = [err.stdout, err.stderr].filter(Boolean).join('\n').trim()
    throw new Error(`${cmd} ${args.join(' ')} failed\n${output}`)
  }
}

describe('@busy-app/create-app', { concurrency: 1 }, () => {
  let work
  let appDir
  let tarball

  before(() => {
    work = mkdtempSync(resolve(tmpdir(), 'busy-create-app-'))
    appDir = resolve(work, 'my-app')
  })

  after(() => {
    rmSync(work, { recursive: true, force: true })
  })

  test('packs', () => {
    tarball = run('npm', ['pack', '--pack-destination', work], { cwd: ROOT }).trim().split('\n').pop()
    assert.ok(existsSync(resolve(work, tarball)), 'npm pack produced no tarball')
  })

  // From the tarball, so the tests see exactly the published file set.
  test('installs the generator from the tarball', () => {
    run('npm', ['install', '--no-save', '--silent', resolve(work, tarball)], { cwd: work })
    assert.ok(existsSync(resolve(work, 'node_modules/.bin/busy-create-app')))
  })

  test('scaffolds an app', () => {
    // Every field as a flag, so nothing is asked and stdin stays closed.
    run(
      resolve(work, 'node_modules/.bin/busy-create-app'),
      [
        'my-app',
        '--id', APP_ID,
        '--name', APP_NAME,
        '--description', APP_DESCRIPTION,
        '--author', APP_AUTHOR,
      ],
      { cwd: work, input: '' },
    )
    assert.ok(existsSync(appDir), 'the generator produced no app folder')
  })

  test('fills the placeholders in', () => {
    const manifest = JSON.parse(readFileSync(resolve(appDir, 'src/appmeta/manifest.json'), 'utf8'))
    assert.equal(manifest.id, APP_ID)
    assert.equal(manifest.name, APP_NAME)
    assert.equal(manifest.description, APP_DESCRIPTION)
    assert.equal(manifest.author, APP_AUTHOR)

    // Not asked for: the package is private, so the name comes from the folder.
    const pkg = JSON.parse(readFileSync(resolve(appDir, 'package.json'), 'utf8'))
    assert.equal(pkg.name, 'my-app')

    // npm strips .gitignore from tarballs; the generator restores it from _gitignore.
    for (const file of ['.gitignore', '.env.example', 'package.json', 'README.md']) {
      assert.ok(existsSync(resolve(appDir, file)), `${file} is missing`)
    }

    // grep exits 1 when it finds nothing — the outcome this test wants.
    let left = ''
    try {
      left = execFileSync('grep', ['-rlE', '(^|[^$])\\{\\{', appDir], { encoding: 'utf8' }).trim()
    } catch (err) {
      if (err.status !== 1) throw err
    }
    assert.equal(left, '', `unfilled placeholders in:\n${left}`)
  })

  test('installs', () => {
    // --engine-strict: the app pins a Node range, so a wrong version fails here rather than further down.
    run('pnpm', ['install', '--silent', '--engine-strict'], { cwd: appDir })
  })

  test('type-checks', () => {
    run('pnpm', ['typecheck'], { cwd: appDir })
  })

  test('builds a package', () => {
    run('pnpm', ['build'], { cwd: appDir })
    // The package folder is named after the manifest id.
    const dist = resolve(appDir, 'dist', APP_ID)

    for (const file of EXPECTED) {
      assert.ok(existsSync(resolve(dist, file)), `dist/${file} is missing`)
    }
    for (const file of FORBIDDEN) {
      assert.ok(!existsSync(resolve(dist, file)), `dist/${file} should not be packaged`)
    }

    // Only the app's own modules get a file of their own, and this one has none.
    assert.deepEqual(readdirSync(resolve(dist, 'scripts')), ['main.js'])
  })

  test('packages resources', () => {
    // A file in src/images/ lands in the package's images/; one loose in src/ is sorted by extension into the same place.
    mkdirSync(resolve(appDir, 'src/images'), { recursive: true })
    writeFileSync(resolve(appDir, 'src/images/icon.png'), '')
    writeFileSync(resolve(appDir, 'src/loose.png'), '')
    try {
      run('pnpm', ['build'], { cwd: appDir })
      for (const file of ['images/icon.png', 'images/loose.png']) {
        assert.ok(existsSync(resolve(appDir, 'dist', APP_ID, file)), `${file} is missing`)
      }
    } finally {
      rmSync(resolve(appDir, 'src/images'), { recursive: true, force: true })
      rmSync(resolve(appDir, 'src/loose.png'), { force: true })
    }
  })

  test('gives each app module its own chunk', () => {
    // Modules beside main.ts and in subfolders, each expected to be split out while shared/ and the dependencies stay inlined. Functions rather than constants: a lone constant is inlined and its chunk disappears.
    //
    // The two format.ts check that chunks named after the module's path under src/ keep same-named modules apart.
    mkdirSync(resolve(appDir, 'src/lib'), { recursive: true })
    mkdirSync(resolve(appDir, 'src/other'), { recursive: true })
    writeFileSync(
      resolve(appDir, 'src/greeting.ts'),
      'export function greeting(n: number): string {\n  return `Hi ${n}`;\n}\n',
    )
    writeFileSync(
      resolve(appDir, 'src/lib/format.ts'),
      'export function pad(n: number): string {\n  return String(n).padStart(2, "0");\n}\n',
    )
    writeFileSync(
      resolve(appDir, 'src/other/format.ts'),
      'export function wrap(s: string): string {\n  return `[${s}]`.repeat(1);\n}\n',
    )

    const main = resolve(appDir, 'src/main.ts')
    const original = readFileSync(main, 'utf8')
    const patched = original.replace('text: "Hello"', 'text: wrap(greeting(ticks)) + pad(ticks)')
    assert.notEqual(patched, original, 'the test could not patch main.ts')
    writeFileSync(
      main,
      'import { greeting } from "./greeting.ts";\n' +
        'import { pad } from "./lib/format.ts";\n' +
        'import { wrap } from "./other/format.ts";\n' +
        patched,
    )

    try {
      run('pnpm', ['typecheck'], { cwd: appDir })
      run('pnpm', ['build'], { cwd: appDir })

      assert.deepEqual(readdirSync(resolve(appDir, 'dist', APP_ID, 'scripts')).sort(), [
        'greeting.js',
        'lib-format.js',
        'main.js',
        'other-format.js',
      ])
      // Same name, different folders: the two must not be merged.
      const lib = readFileSync(resolve(appDir, 'dist', APP_ID, 'scripts/lib-format.js'), 'utf8')
      assert.match(lib, /padStart/, 'lib-format.js lost its module')
    } finally {
      writeFileSync(main, original)
      rmSync(resolve(appDir, 'src/greeting.ts'), { force: true })
      rmSync(resolve(appDir, 'src/lib'), { recursive: true, force: true })
      rmSync(resolve(appDir, 'src/other'), { recursive: true, force: true })
    }
  })

  test('redirects the build with --out', () => {
    run('pnpm', ['build', '--out', '../elsewhere'], { cwd: appDir })
    assert.ok(
      existsSync(resolve(work, 'elsewhere', APP_ID, 'scripts/main.js')),
      '--out did not redirect the build',
    )
  })

  test('packs a tgz alongside the folder with --tgz', () => {
    run('pnpm', ['build', '--tgz'], { cwd: appDir })
    const dist = resolve(appDir, 'dist')

    assert.ok(existsSync(resolve(dist, `${APP_ID}.tgz`)), 'the archive is missing')
    assert.ok(existsSync(resolve(dist, APP_ID, 'scripts/main.js')), '--tgz dropped the folder')

    // The archive holds the <id>/ folder itself, ready to unpack as-is.
    const listing = run('tar', ['-tzf', resolve(dist, `${APP_ID}.tgz`)])
    assert.match(listing, new RegExp(`^${APP_ID}/appmeta/manifest\\.json$`, 'm'))
    assert.match(listing, new RegExp(`^${APP_ID}/scripts/main\\.js$`, 'm'))
  })

  test('leaves only the tgz with --tgz-only', () => {
    run('pnpm', ['build', '--tgz-only'], { cwd: appDir })
    const dist = resolve(appDir, 'dist')

    assert.ok(existsSync(resolve(dist, `${APP_ID}.tgz`)), 'the archive is missing')
    assert.ok(!existsSync(resolve(dist, APP_ID)), '--tgz-only left the folder behind')
  })

  test('rejects an id longer than 32 characters', () => {
    const tooLong = `app.example.${'x'.repeat(32)}`
    assert.throws(
      () =>
        run(resolve(work, 'node_modules/.bin/busy-create-app'), ['long', '--id', tooLong], {
          cwd: work,
          input: '',
        }),
      /32 characters/,
    )
  })

  test('leaves the repository out with --no-git', () => {
    const dir = resolve(work, 'no-git')
    run(
      resolve(work, 'node_modules/.bin/busy-create-app'),
      ['no-git', '--id', 'app.example.no-git', '--name', 'No Git', '--description', 'd', '--author', APP_AUTHOR, '--no-git'],
      { cwd: work, input: '' },
    )
    assert.ok(existsSync(resolve(dir, 'src/main.ts')), 'the app is missing')
    assert.ok(!existsSync(resolve(dir, '.git')), '--no-git still initialized a repository')
  })

  test('defaults to a placeholder namespace', () => {
    const dir = resolve(work, 'defaults')
    run(resolve(work, 'node_modules/.bin/busy-create-app'), ['defaults'], {
      cwd: work,
      // Enter through every prompt; spare newlines are harmless.
      input: '\n'.repeat(8),
    })
    const manifest = JSON.parse(readFileSync(resolve(dir, 'src/appmeta/manifest.json'), 'utf8'))
    assert.equal(manifest.id, 'app.example.defaults')
  })
})
